name: finchandbeans
favicon: null
layout_spectrum: 0.33457643003202975
typography_spectrum: 0.44583391514606774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4303629747591913
  lightness: 0.4933868816588074
  saturation: 0.7180709021631628
  rhythmicContrast: 0.8180212418083102
purpose: []
